### ISSUE TITLE
error: runLinkPrediction_ppi

### ISSUE THREAD

**Issue by vidarmehr** [monarch-initiative/N2V#129]
I get the error messages when I run run_link_prediction in develop branch:

> Traceback (most recent call last):
  File "/Users/ravanv/PycharmProjects/N2V/runLinkPrediction_ppi.py", line 177, in <module>
    main(args)
  File "/Users/ravanv/PycharmProjects/N2V/runLinkPrediction_ppi.py", line 171, in main
    learn_embeddings(walks, pos_train_graph, args.w2v_model)
  File "/Users/ravanv/PycharmProjects/N2V/runLinkPrediction_ppi.py", line 117, in learn_embeddings
    model.train(display_step=100)
  File "/Users/ravanv/PycharmProjects/N2V/xn2v/word2vec.py", line 679, in train
    batch_x, batch_y = self.generate_batch_cbow(sentence)
  File "/Users/ravanv/PycharmProjects/N2V/xn2v/word2vec.py", line 592, in generate_batch_cbow
    sentence = sentence.numpy()
AttributeError: 'list' object has no attribute 'numpy'

**Comment by vidarmehr** [comment]
I removed model.train() from the function call and now runLinkPrediction_ppi.py runs with no error.
