### ISSUE TITLE
add get batch from list of lists for CBOW

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/N2V#31]
Consider adding this to superclass

**Comment by pnrobinson** [comment]
This is the problem -- this APPEND changes the shape (it flattens).
About to board

 current_batch, current_labels = self.generate_batch_cbow(sentence, batch_count, skip_window)
            batch = np.append(batch, current_batch)
            labels = np.append(labels, current_labels, axis=0)

**Comment by justaddcoffee** [comment]
When I run this:
`python runAnalysis.py disease-gene-embeddings -t ppt_train.txt -s 5000 -a cbow -n 3`

I get the following error on [this line](https://github.com/TheJacksonLaboratory/N2V/blob/8c0224dd12e7fc4678be34d4a68e29ad381a07b3/n2v/word2vec.py#L518):

```
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jtr4v/PycharmProjects/N2V/runAnalysis.py", line 98, in <module>
    cli()
  File "/Users/jtr4v/PycharmProjects/N2V/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jtr4v/PycharmProjects/N2V/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/jtr4v/PycharmProjects/N2V/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jtr4v/PycharmProjects/N2V/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jtr4v/PycharmProjects/N2V/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/jtr4v/PycharmProjects/N2V/runAnalysis.py", line 70, in disease_gene_embeddings
    model.train(display_step=display_step)
  File "/Users/jtr4v/PycharmProjects/N2V/n2v/word2vec.py", line 587, in train
    batch_x, batch_y = self.generate_batch_cbow(self.data, self.batch_size, self.skip_window)
  File "/Users/jtr4v/PycharmProjects/N2V/n2v/word2vec.py", line 518, in generate_batch_cbow
    batch[i, col_idx] = buffer[j]
ValueError: setting an array element with a sequence.

Process finished with exit code 1
```

**Comment by pnrobinson** [comment]
I think this issue is stale -- we are going to be refactoring to TF2 anyway and the original function now seems to be working.
