### ISSUE TITLE
travis complaining

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/N2V#59]
test_word2vec.py", line 76,
is causing problems because travis cannot find the input file. I switched the relative to a calculated absolute path but this did not fix the problem. I am unsure what this issue is, does anybody have an idea?
```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/monarch-initiative/N2V/tests/test_word2vec.py", line 76, in setUp
    training_graph = CSFGraph(pos_train)

  File "/home/travis/build/monarch-initiative/N2V/xn2v/csf_graph/csf_graph.py", line 18, in __init__
    raise TypeError("Could not find graph file {}".format(filepath))

TypeError: Could not find graph file /home/travis/build/monarch-initiative/N2V/data/ppismall/pos_train_edges
```

**Comment by pnrobinson** [comment]
fixed
